server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ZUUL
  redis:
    host: 192.168.59.10
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"

#zuul:
#  ignored-services:
#    - "ZUUL"
#  ignored-patterns:
#    - /search/**

#  routes:
#    customer:
#      serviceId: customer
#      path: /cust/**

#  routes:
#    customer: /c/**

